//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGx.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PGx.Model.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string AdditionalInstruction {
            get {
                return ResourceManager.GetString("AdditionalInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回列表 的本地化字符串。
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 药物有效成分 的本地化字符串。
        /// </summary>
        public static string Chemical {
            get {
                return ResourceManager.GetString("Chemical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 药品 的本地化字符串。
        /// </summary>
        public static string ChemicalList {
            get {
                return ResourceManager.GetString("ChemicalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要上传的文件 的本地化字符串。
        /// </summary>
        public static string ChooseFileToBeUploaded {
            get {
                return ResourceManager.GetString("ChooseFileToBeUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除本条目？ 的本地化字符串。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新条目 的本地化字符串。
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据分析 的本地化字符串。
        /// </summary>
        public static string DataProcess {
            get {
                return ResourceManager.GetString("DataProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除条目 的本地化字符串。
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基因双倍型 的本地化字符串。
        /// </summary>
        public static string Diplotype {
            get {
                return ResourceManager.GetString("Diplotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据患者的{0}基因分型测试结果{1}，该患者的药物基因表型属于{2}，这意味着在使用药品{3}时{4}，据此，药物使用推荐建议为：{5}。更多信息请咨询临床药师。 的本地化字符串。
        /// </summary>
        public static string DosingRecomendation {
            get {
                return ResourceManager.GetString("DosingRecomendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 药物 的本地化字符串。
        /// </summary>
        public static string Drug {
            get {
                return ResourceManager.GetString("Drug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名称 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 的本地化字符串。
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件类型 的本地化字符串。
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基因 的本地化字符串。
        /// </summary>
        public static string GeneList {
            get {
                return ResourceManager.GetString("GeneList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基因单倍型 的本地化字符串。
        /// </summary>
        public static string Haplotype {
            get {
                return ResourceManager.GetString("Haplotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 药物基因组学知识库 的本地化字符串。
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 知识管理 的本地化字符串。
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只支持下列文件类型: {0} . 的本地化字符串。
        /// </summary>
        public static string Message_FileTypeInvalid {
            get {
                return ResourceManager.GetString("Message_FileTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}基因分型测试对于药品{1}的使用有重要意义。目前，没有查询到该患者{2}的基因分型测试结果，可能是该患者未进行该项测试，或者测试未完成，在此之前建议使用其他药品。更多信息请咨询临床药师。 的本地化字符串。
        /// </summary>
        public static string NonTestAlert {
            get {
                return ResourceManager.GetString("NonTestAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基因表型 的本地化字符串。
        /// </summary>
        public static string Phenotype {
            get {
                return ResourceManager.GetString("Phenotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用药建议 的本地化字符串。
        /// </summary>
        public static string Recomendation {
            get {
                return ResourceManager.GetString("Recomendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐等级 的本地化字符串。
        /// </summary>
        public static string RecomendationLevel {
            get {
                return ResourceManager.GetString("RecomendationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样品编码 的本地化字符串。
        /// </summary>
        public static string SampleCode {
            get {
                return ResourceManager.GetString("SampleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件 的本地化字符串。
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传 的本地化字符串。
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件 的本地化字符串。
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zhejiang University 的本地化字符串。
        /// </summary>
        public static string ZJU {
            get {
                return ResourceManager.GetString("ZJU", resourceCulture);
            }
        }
    }
}
