//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGx.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefinitionFile
    {
        public DefinitionFile()
        {
            this.VariantLocus = new HashSet<VariantLocus>();
            this.NamedAllele = new HashSet<NamedAllele>();
            this.PhenotypeMap = new HashSet<NamedPhenotype>();
            this.PGxGuideline = new HashSet<PGxGuideline>();
        }
    
        public int ID { get; set; }
        public string FormatVersion { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public string GeneSymbol { get; set; }
        public string Orientation { get; set; }
        public string Chromosome { get; set; }
        public string GenomeBuild { get; set; }
        public string RefSeqChromosome { get; set; }
        public string RefSeqGene { get; set; }
        public string RefSeqProtein { get; set; }
        public string Notes { get; set; }
        public string Populations { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
        public string GeneName { get; set; }
        public string NamedFunctions { get; set; }
        public string AlleleFrequencyTable { get; set; }
        public string FunctionTable { get; set; }
        public string AlleleDefinitionTable { get; set; }
        public string DiplotypePhenotypeTable { get; set; }
        public string IsAvailable { get; set; }
    
        public virtual ICollection<VariantLocus> VariantLocus { get; set; }
        public virtual ICollection<NamedAllele> NamedAllele { get; set; }
        public virtual ICollection<NamedPhenotype> PhenotypeMap { get; set; }
        public virtual ICollection<PGxGuideline> PGxGuideline { get; set; }
    }
}
