//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGx.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefinitionExemption
    {
        public DefinitionExemption()
        {
            this.ExtraPositions = new HashSet<VariantLocus>();
        }
    
        public int ID { get; set; }
        public string Gene { get; set; }
        public bool AllHits { get; set; }
        public bool AssumeReference { get; set; }
        public string IgnoredAlleles { get; set; }
        public string IgnoredAllelesLc { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
    
        public virtual ICollection<VariantLocus> ExtraPositions { get; set; }
    }
}
