//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGx.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiplotypeResult
    {
        public int ID { get; set; }
        public string GeneSymbol { get; set; }
        public string Diplotype { get; set; }
        public string PHenotype { get; set; }
        public string AlleleA { get; set; }
        public string AlleleB { get; set; }
        public int RAW_DATA_FILEID { get; set; }
    
        public virtual RAW_DATA_FILE RAW_DATA_FILE { get; set; }
    }
}
