//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGx.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DosingGuidence
    {
        public DosingGuidence()
        {
            this.RecommendationPhenotype = new HashSet<RecommendationPhenotype>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phenotype { get; set; }
        public string Strength { get; set; }
        public string RxChange { get; set; }
        public string Implication { get; set; }
        public string Recommendation { get; set; }
        public int PGxGuidelineID { get; set; }
        public Nullable<int> Proportion { get; set; }
        public string Additional { get; set; }
        public string Alternative { get; set; }
        public Nullable<bool> Contraindicated { get; set; }
        public Nullable<int> ProportionMax { get; set; }
        public string Frequency { get; set; }
        public string ImpactLevel { get; set; }
    
        public virtual PGxGuideline PGxGuideline { get; set; }
        public virtual ICollection<RecommendationPhenotype> RecommendationPhenotype { get; set; }
    }
}
