//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGx.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneCall
    {
        public GeneCall()
        {
            this.DiplotypeMatch = new HashSet<DiplotypeMatch>();
            this.HaplotypeMatch = new HashSet<HaplotypeMatch>();
            this.Variants = new HashSet<Variant>();
            this.VarOfInterest = new HashSet<VarOfInterest>();
        }
    
        public int ID { get; set; }
        public string AlleleDefinitionVersion { get; set; }
        public string Chromosome { get; set; }
        public string Gene { get; set; }
        public Nullable<bool> IsPhased { get; set; }
        public string UncallableHaplotypes { get; set; }
        public string IgnoredHaplotypes { get; set; }
        public Nullable<int> FileId { get; set; }
        public string TimeStamp { get; set; }
        public Nullable<bool> IsVcfCall { get; set; }
        public int RAW_DATA_FILEID { get; set; }
        public string HaplotypeA { get; set; }
        public string HaplotypeB { get; set; }
        public string Diplotype { get; set; }
        public string Phenotype { get; set; }
    
        public virtual ICollection<DiplotypeMatch> DiplotypeMatch { get; set; }
        public virtual ICollection<HaplotypeMatch> HaplotypeMatch { get; set; }
        public virtual ICollection<Variant> Variants { get; set; }
        public virtual ICollection<VarOfInterest> VarOfInterest { get; set; }
        public virtual RAW_DATA_FILE RAW_DATA_FILE { get; set; }
    }
}
