//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGx.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaplotypeMatch
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string M_function { get; set; }
        public string Sequences { get; set; }
        public int GeneCallID { get; set; }
    
        public virtual GeneCall GeneCall { get; set; }
    }
}
