//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGx.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Literature
    {
        public int ID { get; set; }
        public string M_title { get; set; }
        public string M_journal { get; set; }
        public Nullable<int> M_year { get; set; }
        public string M_pmid { get; set; }
        public string M_authors { get; set; }
        public int PGxGuidelineID { get; set; }
    
        public virtual PGxGuideline PGxGuideline { get; set; }
    }
}
