//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGx.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamedPhenotype
    {
        public NamedPhenotype()
        {
            this.PhenotypeDef = new HashSet<PhenotypeDef>();
            this.PhenotypePopFreq = new HashSet<PhenotypePopFreq>();
        }
    
        public int ID { get; set; }
        public string Symbol { get; set; }
        public string Phenotype { get; set; }
        public string Description { get; set; }
        public int DefinitionFileID { get; set; }
        public string GenotypeList { get; set; }
        public string ActivityScore { get; set; }
    
        public virtual DefinitionFile DefinitionFile { get; set; }
        public virtual ICollection<PhenotypeDef> PhenotypeDef { get; set; }
        public virtual ICollection<PhenotypePopFreq> PhenotypePopFreq { get; set; }
    }
}
