//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGx.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PGx_KBEntities : DbContext
    {
        public PGx_KBEntities()
            : base("name=PGx_KBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RAW_DATA_FILE> RAW_DATA_FILE { get; set; }
       
        public DbSet<DefinitionFile> DefinitionFile { get; set; }
        public DbSet<VariantLocus> VariantLocus { get; set; }
        public DbSet<NamedAllele> NamedAllele { get; set; }
        public DbSet<NamedAlleleDefinition> NamedAlleleDefinition { get; set; }
        public DbSet<DefinitionExemption> DefinitionExemption { get; set; }
        public DbSet<PopulationFrequency> PopulationFrequency { get; set; }
        public DbSet<PGxGuideline> PGxGuideline { get; set; }
        public DbSet<RelatedGene> RelatedGene { get; set; }
        public DbSet<DosingGuidence> DosingGuidence { get; set; }
        public DbSet<Literature> Literature { get; set; }
        public DbSet<GeneCall> GeneCall { get; set; }
        public DbSet<DiplotypeMatch> DiplotypeMatch { get; set; }
        public DbSet<HaplotypeMatch> HaplotypeMatch { get; set; }
        public DbSet<Variant> Variant { get; set; }
        public DbSet<VarOfInterest> VarOfInterest { get; set; }
        public DbSet<NamedPhenotype> NamedPhenotype { get; set; }
        public DbSet<PhenotypeDef> PhenotypeDef { get; set; }      
        public DbSet<PhenotypePopFreq> PhenotypePopFreq { get; set; }
        public DbSet<Patient> Patient { get; set; }
        public DbSet<DiplotypeResult> DiplotypeResult { get; set; }
        public DbSet<ClinicalRelevance> ClinicalRelevance { get; set; }
        public DbSet<RecommendationPhenotype> RecommendationPhenotype { get; set; }
    }
}
