//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGx.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAW_DATA_FILE
    {
        public RAW_DATA_FILE()
        {
            this.DiplotypeResult = new HashSet<DiplotypeResult>();
            this.GeneCall = new HashSet<GeneCall>();
        }
    
        public int ID { get; set; }
        public string PatientName { get; set; }
        public string SampleCode { get; set; }
        public string FILE_PATH { get; set; }
        public string TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Method { get; set; }
        public string Laboratory { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string PatientID { get; set; }
        public string FileType { get; set; }
    
        public virtual ICollection<DiplotypeResult> DiplotypeResult { get; set; }
        public virtual ICollection<GeneCall> GeneCall { get; set; }
    }
}
