//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGx.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantLocus
    {
        public VariantLocus()
        {
            this.AlleleDefinition = new HashSet<NamedAlleleDefinition>();
        }
    
        public int ID { get; set; }
        public string Chromosome { get; set; }
        public int Position { get; set; }
        public string Rsid { get; set; }
        public string ChromosomeHgvsName { get; set; }
        public string GeneHgvsName { get; set; }
        public string ProteinNote { get; set; }
        public string ResourceNote { get; set; }
        public string Type { get; set; }
        public string ReferenceRepeat { get; set; }
        public Nullable<int> DefinitionFileID { get; set; }
        public string Alleles { get; set; }
        public Nullable<int> DefinitionExemptionID { get; set; }
        public string TranscriptName { get; set; }
    
        public virtual DefinitionFile DefinitionFile { get; set; }
        public virtual ICollection<NamedAlleleDefinition> AlleleDefinition { get; set; }
        public virtual DefinitionExemption DefinitionExemption { get; set; }
    }
}
