//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.App.Utility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.App.Utility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[&quot;啊&quot;,&quot;a1&quot;,&quot;B0A1&quot;,&quot;True&quot;],[&quot;阿&quot;,&quot;a1&quot;,&quot;B0A2&quot;,&quot;True&quot;],[&quot;吖&quot;,&quot;a1&quot;,&quot;DFB9&quot;,&quot;False&quot;],[&quot;腌&quot;,&quot;a1&quot;,&quot;EBE7&quot;,&quot;True&quot;],[&quot;锕&quot;,&quot;a1&quot;,&quot;EFB9&quot;,&quot;False&quot;],[&quot;啊&quot;,&quot;a2&quot;,&quot;B0A1&quot;,&quot;True&quot;],[&quot;嗄&quot;,&quot;a2&quot;,&quot;E0C4&quot;,&quot;True&quot;],[&quot;啊&quot;,&quot;a3&quot;,&quot;B0A1&quot;,&quot;True&quot;],[&quot;啊&quot;,&quot;a4&quot;,&quot;B0A1&quot;,&quot;True&quot;],[&quot;啊&quot;,&quot;a5&quot;,&quot;B0A1&quot;,&quot;True&quot;],[&quot;呵&quot;,&quot;a5&quot;,&quot;BAC7&quot;,&quot;True&quot;],[&quot;埃&quot;,&quot;ai1&quot;,&quot;B0A3&quot;,&quot;False&quot;],[&quot;挨&quot;,&quot;ai1&quot;,&quot;B0A4&quot;,&quot;True&quot;],[&quot;哎&quot;,&quot;ai1&quot;,&quot;B0A5&quot;,&quot;True&quot;],[&quot;唉&quot;,&quot;ai1&quot;,&quot;B0A6&quot;,&quot;True&quot;],[&quot;哀&quot;,&quot;ai1&quot;,&quot;B....
        /// </summary>
        internal static string Pinyin_cn {
            get {
                return ResourceManager.GetString("Pinyin_cn", resourceCulture);
            }
        }
    }
}
